#!/usr/bin/env bash

# Interactive AP/STA configuration entry point for onboard WiFi on the X5
# Buildroot image.
set -u

IFACE="${WIFI_IFACE:-wlan0}"
BASE_DIR="${WIFI_MANAGER_DIR:-/userdata/wifi}"
SCRIPT_PATH="${WIFI_SCRIPT_PATH:-/userdata/wifi_setup.sh}"
STATE_FILE="$BASE_DIR/current.conf"
HOSTAPD_CONF="$BASE_DIR/hostapd.conf"
WPA_CONF="$BASE_DIR/wpa_supplicant.conf"
SCAN_FILE="$BASE_DIR/scan_ssids.txt"
LOG_DIR="$BASE_DIR/logs"
HOSTAPD_LOG="$LOG_DIR/hostapd.log"
DNSMASQ_LOG="$LOG_DIR/dnsmasq.log"
WPA_LOG="$LOG_DIR/wpa_supplicant.log"
AUTOSTART_FILE="${WIFI_AUTOSTART_FILE:-/userdata/startup.sh}"
LEGACY_BOOT_FILE="${WIFI_LEGACY_BOOT_FILE:-/etc/init.d/S41wifi_manager}"
AUTOSTART_MARKER="WIFI_AUTOSTART_MANAGED"
DNSMASQ_PID="$BASE_DIR/dnsmasq.pid"
DEFAULT_AP_SSID="RoboBaton-X5"
DEFAULT_AP_IP="192.168.5.1"
DEFAULT_AP_CHANNEL="1"
DEFAULT_DHCP_START="192.168.5.2"
DEFAULT_DHCP_END="192.168.5.254"

info() { printf '%s\n' "$*"; }
warn() { printf 'WARN: %s\n' "$*" >&2; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

need_root() {
    [ "$(id -u)" = "0" ] || die "Run as root: $SCRIPT_PATH"
}

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "Missing command: $1"
}

check_deps() {
    need_cmd ip
    need_cmd iw
    need_cmd hostapd
    need_cmd dnsmasq
    need_cmd wpa_supplicant
    need_cmd wpa_cli
    need_cmd udhcpc
    need_cmd killall
    need_cmd awk
    need_cmd sed
}

ensure_dirs() {
    mkdir -p "$BASE_DIR" "$LOG_DIR" || die "Failed to create directory: $BASE_DIR"
    chmod 700 "$BASE_DIR" >/dev/null 2>&1 || true
}

escape_wpa_string() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    printf '%s' "$value"
}

write_state_kv() {
    local key="$1"
    local value="$2"
    printf '%s=' "$key"
    printf '%q\n' "$value"
}

save_ap_state() {
    local ssid="$1"
    local psk="$2"
    local channel="$3"
    local ap_ip="$4"
    local dhcp_start="$5"
    local dhcp_end="$6"
    local tmp="$STATE_FILE.tmp"

    {
        write_state_kv MODE ap
        write_state_kv IFACE "$IFACE"
        write_state_kv AP_SSID "$ssid"
        write_state_kv AP_PSK "$psk"
        write_state_kv AP_CHANNEL "$channel"
        write_state_kv AP_IP "$ap_ip"
        write_state_kv DHCP_START "$dhcp_start"
        write_state_kv DHCP_END "$dhcp_end"
    } > "$tmp" || die "Failed to write configuration: $tmp"
    chmod 600 "$tmp" >/dev/null 2>&1 || true
    mv "$tmp" "$STATE_FILE" || die "Failed to save configuration: $STATE_FILE"
}

save_sta_state() {
    local ssid="$1"
    local psk="$2"
    local tmp="$STATE_FILE.tmp"

    {
        write_state_kv MODE sta
        write_state_kv IFACE "$IFACE"
        write_state_kv STA_SSID "$ssid"
        write_state_kv STA_PSK "$psk"
    } > "$tmp" || die "Failed to write configuration: $tmp"
    chmod 600 "$tmp" >/dev/null 2>&1 || true
    mv "$tmp" "$STATE_FILE" || die "Failed to save configuration: $STATE_FILE"
}

load_state() {
    [ -f "$STATE_FILE" ] || die "No saved WiFi configuration: $STATE_FILE"
    # current.conf is generated by this script with bash %q. Source only the
    # controlled configuration to avoid parsing arbitrary input.
    # shellcheck disable=SC1090
    . "$STATE_FILE"
}

valid_ipv4_like() {
    case "$1" in
        *[!0-9.]*|''|*..*|.*|*.) return 1 ;;
        *) return 0 ;;
    esac
}

valid_channel_24g() {
    case "$1" in
        ''|*[!0-9]*) return 1 ;;
        *) [ "$1" -ge 1 ] 2>/dev/null && [ "$1" -le 13 ] 2>/dev/null ;;
    esac
}

read_default() {
    local prompt="$1"
    local default_value="$2"
    local answer
    read -r -p "$prompt [$default_value]: " answer
    if [ -z "$answer" ]; then
        printf '%s' "$default_value"
    else
        printf '%s' "$answer"
    fi
}

read_secret() {
    local prompt="$1"
    local answer
    read -r -s -p "$prompt" answer
    printf '\n' >&2
    printf '%s' "$answer"
}

confirm() {
    local prompt="$1"
    local answer
    read -r -p "$prompt [y/N]: " answer
    case "$answer" in
        y|Y|yes|YES|Yes) return 0 ;;
        *) return 1 ;;
    esac
}

autostart_is_managed() {
    [ -f "$AUTOSTART_FILE" ] || return 1
    [ -n "$(sed -n "/$AUTOSTART_MARKER/p" "$AUTOSTART_FILE" 2>/dev/null)" ]
}

stop_wifi_processes() {
    # Release wlan0 before switching AP/STA to avoid hostapd/wpa_supplicant/
    # dnsmasq competing for the interface.
    killall hostapd >/dev/null 2>&1 || true
    killall wpa_supplicant >/dev/null 2>&1 || true
    killall udhcpc >/dev/null 2>&1 || true

    if [ -f "$DNSMASQ_PID" ]; then
        local pid
        pid="$(cat "$DNSMASQ_PID" 2>/dev/null || true)"
        if [ -n "$pid" ] && [ -d "/proc/$pid" ]; then
            kill "$pid" >/dev/null 2>&1 || true
        fi
        rm -f "$DNSMASQ_PID" >/dev/null 2>&1 || true
    fi

    # Support old pidfile-less dnsmasq started by wifi_init.sh, avoiding the old
    # DHCP service continuing to occupy wlan0.
    killall dnsmasq >/dev/null 2>&1 || true
}

disable_wifi_runtime() {
    # Explicit WiFi disable stops processes, clears addresses, and brings down
    # the wlan0 radio interface.
    # Do not unload the aic8800 kernel module to avoid affecting Bluetooth/driver
    # lifetime; handle full power-down manually when needed.
    stop_wifi_processes
    ip addr flush dev "$IFACE" >/dev/null 2>&1 || true
    ip link set "$IFACE" down >/dev/null 2>&1 || true
    info "WiFi disabled: processes stopped, $IFACE is down; kernel driver not unloaded."
}

prompt_disable_wifi() {
    disable_wifi_runtime
    if confirm "Disable WiFi auto-start at boot as well?"; then
        remove_autostart
    fi
}

reset_interface() {
    ip addr flush dev "$IFACE" >/dev/null 2>&1 || true
    ip link set "$IFACE" down >/dev/null 2>&1 || true
    sleep 1
    ip link set "$IFACE" up || die "Failed to bring up interface: $IFACE"
    sleep 1
}

write_hostapd_config() {
    local ssid="$1"
    local psk="$2"
    local channel="$3"

    cat > "$HOSTAPD_CONF" <<EOF_AP
interface=$IFACE
driver=nl80211
ssid=$ssid
hw_mode=g
channel=$channel
beacon_int=100
dtim_period=2
max_num_sta=32
auth_algs=1
ignore_broadcast_ssid=0
wmm_enabled=1
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
EOF_AP

    if [ -n "$psk" ]; then
        cat >> "$HOSTAPD_CONF" <<EOF_AP_SEC
wpa=2
wpa_passphrase=$psk
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
rsn_pairwise=CCMP
EOF_AP_SEC
    fi

    chmod 600 "$HOSTAPD_CONF" >/dev/null 2>&1 || true
}

write_wpa_config() {
    local ssid="$1"
    local psk="$2"
    local ssid_escaped
    local psk_escaped
    ssid_escaped="$(escape_wpa_string "$ssid")"
    psk_escaped="$(escape_wpa_string "$psk")"

    cat > "$WPA_CONF" <<EOF_WPA
ctrl_interface=/var/run/wpa_supplicant
update_config=1
ap_scan=1
country=CN

network={
    ssid="$ssid_escaped"
EOF_WPA

    if [ -n "$psk" ]; then
        cat >> "$WPA_CONF" <<EOF_WPA_SEC
    psk="$psk_escaped"
    key_mgmt=WPA-PSK
EOF_WPA_SEC
    else
        cat >> "$WPA_CONF" <<EOF_WPA_OPEN
    key_mgmt=NONE
EOF_WPA_OPEN
    fi

    cat >> "$WPA_CONF" <<EOF_WPA_END
}
EOF_WPA_END
    chmod 600 "$WPA_CONF" >/dev/null 2>&1 || true
}

start_ap_runtime() {
    local ssid="$1"
    local psk="$2"
    local channel="$3"
    local ap_ip="$4"
    local dhcp_start="$5"
    local dhcp_end="$6"

    write_hostapd_config "$ssid" "$psk" "$channel"
    stop_wifi_processes
    reset_interface
    ip addr add "$ap_ip/24" dev "$IFACE" || die "Failed to set AP address: $ap_ip/24"

    # AP process output goes to /userdata so background processes do not inherit
    # the terminal and hang SSH remote execution.
    hostapd -B "$HOSTAPD_CONF" > "$HOSTAPD_LOG" 2>&1 || die "hostapd failed to start; check: $HOSTAPD_LOG"
    sleep 1
    dnsmasq --interface="$IFACE" \
        --bind-interfaces \
        --no-resolv \
        --no-poll \
        --dhcp-range="$dhcp_start,$dhcp_end,12h" \
        --dhcp-option="3,$ap_ip" \
        --dhcp-option="6,$ap_ip" \
        --pid-file="$DNSMASQ_PID" \
        > "$DNSMASQ_LOG" 2>&1 &
    sleep 1

    local state
    state="$(wpa_cli -p /var/run/hostapd -i "$IFACE" status 2>/dev/null | awk -F= '$1 == "state" {print $2}')"
    [ "$state" = "ENABLED" ] || die "AP did not enter ENABLED state; check: $HOSTAPD_LOG"

    info "AP started: SSID=$ssid, IP=$ap_ip, DHCP=$dhcp_start-$dhcp_end"
}

wait_sta_connected() {
    local i
    local state
    for i in $(seq 1 25); do
        state="$(wpa_cli -i "$IFACE" status 2>/dev/null | awk -F= '$1 == "wpa_state" {print $2}')"
        [ "$state" = "COMPLETED" ] && return 0
        sleep 1
    done
    return 1
}

start_sta_runtime() {
    local ssid="$1"
    local psk="$2"

    write_wpa_config "$ssid" "$psk"
    stop_wifi_processes
    reset_interface

    # Persist STA connection logs for field diagnosis of wrong passwords,
    # authentication failures, and DHCP failures.
    wpa_supplicant -D nl80211 -i "$IFACE" -c "$WPA_CONF" -B > "$WPA_LOG" 2>&1 || die "wpa_supplicant failed to start; check: $WPA_LOG"
    if ! wait_sta_connected; then
        iw dev "$IFACE" link 2>/dev/null || true
        die "Not connected to SSID=$ssid; check password or signal, and inspect: $WPA_LOG"
    fi

    if udhcpc -i "$IFACE" -q -n -t 5 >/dev/null 2>&1; then
        info "STA connected and obtained a DHCP address."
    else
        warn "STA associated, but DHCP failed; check the router manually or configure a static address."
    fi
    ip addr show dev "$IFACE"
}

scan_ssids() {
    reset_interface
    printf '%s\n' "Scanning WiFi, please wait..." >&2
    iw dev "$IFACE" scan 2>/dev/null \
        | awk -F'SSID: ' '/^[[:space:]]*SSID: / { if (length($2) > 0 && !seen[$2]++) print $2 }' \
        > "$SCAN_FILE"

    if [ ! -s "$SCAN_FILE" ]; then
        return 1
    fi

    awk '{ printf "%2d) %s\n", NR, $0 }' "$SCAN_FILE" >&2
    return 0
}

choose_scanned_ssid() {
    local count
    local choice
    local ssid

    if ! scan_ssids; then
        die "No visible SSID found; check antenna, distance, or hidden networks."
    fi

    count="$(awk 'END {print NR}' "$SCAN_FILE")"
    while true; do
        read -r -p "Select WiFi number, enter r to rescan, or q to quit: " choice
        case "$choice" in
            q|Q) exit 0 ;;
            r|R) scan_ssids || die "Rescan still found no visible SSID"; count="$(awk 'END {print NR}' "$SCAN_FILE")" ;;
            ''|*[!0-9]*) warn "Enter a number from 1 to $count." ;;
            *)
                if [ "$choice" -ge 1 ] 2>/dev/null && [ "$choice" -le "$count" ] 2>/dev/null; then
                    ssid="$(awk -v n="$choice" 'NR == n {print; exit}' "$SCAN_FILE")"
                    printf '%s' "$ssid"
                    return 0
                fi
                warn "Number out of range: 1-$count"
                ;;
        esac
    done
}

prompt_ap_mode() {
    local ssid
    local psk
    local psk2
    local channel
    local ap_ip
    local dhcp_start
    local dhcp_end

    info "Configure AP mode. Leave password empty for an open hotspot; non-empty passwords must be 8-63 characters."
    ssid="$(read_default "AP SSID" "$DEFAULT_AP_SSID")"
    while true; do
        psk="$(read_secret "AP password (may be empty): ")"
        if [ -z "$psk" ]; then
            break
        fi
        if [ "${#psk}" -lt 8 ] || [ "${#psk}" -gt 63 ]; then
            warn "WPA2 password length must be 8-63 characters."
            continue
        fi
        psk2="$(read_secret "Enter AP password again: ")"
        [ "$psk" = "$psk2" ] && break
        warn "Passwords do not match."
    done

    while true; do
        channel="$(read_default "2.4G channel" "$DEFAULT_AP_CHANNEL")"
        valid_channel_24g "$channel" && break
        warn "Channel must be 1-13."
    done

    while true; do
        ap_ip="$(read_default "AP IP, fixed /24 mask" "$DEFAULT_AP_IP")"
        valid_ipv4_like "$ap_ip" && break
        warn "Invalid IP format."
    done

    dhcp_start="$(read_default "DHCP start address" "$DEFAULT_DHCP_START")"
    dhcp_end="$(read_default "DHCP end address" "$DEFAULT_DHCP_END")"

    start_ap_runtime "$ssid" "$psk" "$channel" "$ap_ip" "$dhcp_start" "$dhcp_end"
    save_ap_state "$ssid" "$psk" "$channel" "$ap_ip" "$dhcp_start" "$dhcp_end"
    ask_autostart
}

prompt_sta_mode() {
    local ssid
    local psk

    ssid="$(choose_scanned_ssid)"
    info "Selected SSID: $ssid"
    psk="$(read_secret "WiFi password (empty for open network): ")"

    start_sta_runtime "$ssid" "$psk"
    save_sta_state "$ssid" "$psk"
    ask_autostart
}

write_autostart_file() {
    # Buildroot S99auto_startup runs after /userdata is mounted, so only write a
    # late-boot startup entry here.
    # Keep WiFi configuration in /userdata/wifi/current.conf and restore it after
    # boot through the userdata startup hook.
    cat > "$AUTOSTART_FILE" <<EOF_BOOT
#!/bin/sh
# WIFI_AUTOSTART_MANAGED
# Generated by wifi_setup.sh for S99auto_startup to start WiFi after /userdata is mounted.
/userdata/wifi_setup.sh --apply-saved >/userdata/wifi/boot.log 2>&1
EOF_BOOT
}

install_autostart() {
    ensure_dirs
    chmod +x "$SCRIPT_PATH" >/dev/null 2>&1 || true

    if [ -f "$AUTOSTART_FILE" ] && ! autostart_is_managed; then
        die "Existing $AUTOSTART_FILE was not generated by this script; merge manually before enabling."
    fi

    write_autostart_file || die "Failed to write boot startup script: $AUTOSTART_FILE"
    chmod 755 "$AUTOSTART_FILE" || die "Failed to make boot startup script executable: $AUTOSTART_FILE"

    # Remove old S41 early-start file to prevent it from running before
    # /userdata is mounted and making boot startup appear ineffective.
    rm -f "$LEGACY_BOOT_FILE" >/dev/null 2>&1 || true

    sync
    info "Saved boot startup: $AUTOSTART_FILE"
}

remove_autostart() {
    if [ -f "$AUTOSTART_FILE" ] && autostart_is_managed; then
        rm -f "$AUTOSTART_FILE" >/dev/null 2>&1 || {
            mount -o remount,rw / >/dev/null 2>&1 || true
            rm -f "$AUTOSTART_FILE" || die "Failed to delete boot startup script: $AUTOSTART_FILE"
        }
    fi

    # The old S41 early-start file is obsolete; clean it when disabling boot
    # startup.
    rm -f "$LEGACY_BOOT_FILE" >/dev/null 2>&1 || true

    sync
    info "Disabled boot startup managed by this script."
}

ask_autostart() {
    if confirm "Save/update current WiFi configuration for boot auto-start?"; then
        install_autostart
    else
        remove_autostart
    fi
}

apply_saved() {
    ensure_dirs
    load_state
    IFACE="${IFACE:-wlan0}"
    case "${MODE:-}" in
        ap)
            start_ap_runtime "${AP_SSID:-$DEFAULT_AP_SSID}" "${AP_PSK:-}" "${AP_CHANNEL:-$DEFAULT_AP_CHANNEL}" "${AP_IP:-$DEFAULT_AP_IP}" "${DHCP_START:-$DEFAULT_DHCP_START}" "${DHCP_END:-$DEFAULT_DHCP_END}"
            ;;
        sta)
            [ -n "${STA_SSID:-}" ] || die "STA_SSID is empty; cannot start client mode."
            start_sta_runtime "$STA_SSID" "${STA_PSK:-}"
            ;;
        *)
            die "Unknown saved mode: ${MODE:-empty}"
            ;;
    esac
}

status_wifi() {
    info "=== $IFACE address ==="
    ip addr show dev "$IFACE" 2>/dev/null || true
    info "=== $IFACE info ==="
    iw dev "$IFACE" info 2>/dev/null || true
    info "=== station link ==="
    iw dev "$IFACE" link 2>/dev/null || true
    info "=== hostapd status ==="
    wpa_cli -p /var/run/hostapd -i "$IFACE" status 2>/dev/null || true
    info "=== saved config ==="
    if [ -f "$STATE_FILE" ]; then
        sed -n 's/^MODE=.*/MODE=<saved>/p; s/^AP_SSID=.*/AP_SSID=<saved>/p; s/^STA_SSID=.*/STA_SSID=<saved>/p; s/^AP_IP=.*/AP_IP=<saved>/p' "$STATE_FILE"
    else
        info "none"
    fi
    [ -e "$AUTOSTART_FILE" ] && info "autostart=enabled ($AUTOSTART_FILE)" || info "autostart=disabled"
    [ -e "$LEGACY_BOOT_FILE" ] && info "legacy_autostart=present ($LEGACY_BOOT_FILE)" || info "legacy_autostart=absent"
}

usage() {
    cat <<EOF_USAGE
Usage:
  $SCRIPT_PATH                 Interactively configure AP/client mode
  $SCRIPT_PATH --apply-saved   Start saved configuration from /userdata/wifi/current.conf
  $SCRIPT_PATH --stop          Stop WiFi processes, clear addresses, and bring wlan0 down
  $SCRIPT_PATH --disable       Same as --stop; does not unload the kernel driver
  $SCRIPT_PATH --status        Show wlan0/saved configuration/boot startup status
  $SCRIPT_PATH --help          Show help
EOF_USAGE
}

interactive_menu() {
    while true; do
        cat <<EOF_MENU

Select WiFi mode:
  1) AP mode: turn the board into a hotspot
  2) Client mode: scan and connect to router WiFi
  3) Show status
  4) Disable WiFi (stop services and bring wlan0 down)
  5) Exit
EOF_MENU
        read -r -p "Enter number: " choice
        case "$choice" in
            1) prompt_ap_mode; return 0 ;;
            2) prompt_sta_mode; return 0 ;;
            3) status_wifi ;;
            4) prompt_disable_wifi; return 0 ;;
            5|q|Q) return 0 ;;
            *) warn "Invalid choice: $choice" ;;
        esac
    done
}

main() {
    need_root
    check_deps
    ensure_dirs

    case "${1:-}" in
        --apply-saved) apply_saved ;;
        --stop|--disable) disable_wifi_runtime ;;
        --status) status_wifi ;;
        --help|-h) usage ;;
        '') interactive_menu ;;
        *) usage; exit 1 ;;
    esac
}

main "$@"
